apiVersion: automation.nephio.org/v1alpha1
kind: PackageDeployment
metadata:
  name: openstack-small-cluster
  labels: 
    type: Infra
spec:
  selector:
    matchLabels:
      nephio.org/region: us-central1
      nephio.org/site-type: aggregation
  namespace: default
  kubernetesVersion: v1.24.8
  controlPlaneMachineCount: "3"
  kubernetesMachineCount: "3"
  provider: OpenStack
  provisionMethod: Cluster-API
  podCDIR: "10.244.0.0"
  cniLabel: "flannel"
  controlPlaneMachineFlavor: "cluster.compute"
  kubernetesMachineFlavor: "cluster.compute"
  packageRef:
    repository: template-packages
    packageName: kubernetes-template-cluster-api
    revision: v1